import { LegalPageLayout, LegalSection } from '@/components/legal-page-layout'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: 'The terms and conditions of using SchemeKnit.',
}

export default function TermsPage() {
  return (
    <LegalPageLayout
      title="Terms of Service"
      subtitle="The terms and conditions of using SchemeKnit."
      lastUpdated="September 2026"
    >
      <LegalSection title="1. Acceptance of Terms">
        <p>
          By creating a SchemeKnit account or using the service, you agree to
          these terms. If you do not agree, please do not use the service.
        </p>
      </LegalSection>

      <LegalSection title="2. The Service">
        <p>
          SchemeKnit is a lesson-plan generation platform. It converts
          uploaded schemes of work into individual, classroom-ready lesson
          plans aligned with the Ghana Education Service curriculum
          structure. The service also provides document export (DOCX, PDF,
          XLSX, ZIP) and optional AI-assisted content enrichment.
        </p>
      </LegalSection>

      <LegalSection title="3. Accounts and Roles">
        <ul className="list-disc space-y-1 pl-6">
          <li>
            <strong>Individual Teachers</strong> may use SchemeKnit with a Free
            or Teacher Pro subscription.
          </li>
          <li>
            <strong>Schools</strong> activate a license and manage their
            teachers. School administrators create and manage teacher accounts
            within their school.
          </li>
          <li>
            <strong>Platform administrators</strong> manage the platform,
            schools, and licenses.
          </li>
        </ul>
        <p>
          You are responsible for keeping your password secure. Account access
          is protected by password-based authentication and session tokens.
        </p>
      </LegalSection>

      <LegalSection title="4. Subscriptions and Payments">
        <p>
          Subscription plans are described on our pricing and plan pages.
          Payments are verified manually — we do not process card or
          mobile-money transactions automatically. A subscription activates
          only after payment verification is complete. See our{' '}
          <a href="/license-subscription" className="text-brand-cyan underline">
            License &amp; Subscription Terms
          </a>{' '}
          for details.
        </p>
      </LegalSection>

      <LegalSection title="5. Acceptable Use">
        <ul className="list-disc space-y-1 pl-6">
          <li>Upload only curriculum documents you have the right to use.</li>
          <li>Do not share your account credentials with others.</li>
          <li>Do not attempt to bypass entitlement limits or rate controls.</li>
          <li>Do not use the service for unlawful or harmful purposes.</li>
        </ul>
      </LegalSection>

      <LegalSection title="6. Generated Content">
        <p>
          Lesson plans generated by SchemeKnit are provided for educational
          use. You remain responsible for reviewing and adapting generated
          content to your classroom context before use. AI-enriched content
          is advisory and should be reviewed by the teacher.
        </p>
      </LegalSection>

      <LegalSection title="7. Service Availability">
        <p>
          We aim for high availability but do not guarantee uninterrupted
          service. Scheduled maintenance, updates, and events beyond our
          control may cause temporary unavailability.
        </p>
      </LegalSection>

      <LegalSection title="8. Limitation of Liability">
        <p>
          SchemeKnit is provided "as is" without warranties of any kind. To
          the maximum extent permitted by law, we are not liable for indirect,
          incidental, or consequential damages arising from use of the
          service.
        </p>
      </LegalSection>

      <LegalSection title="9. Changes to Terms">
        <p>
          We may update these terms from time to time. Continued use of the
          service after changes constitutes acceptance of the updated terms.
        </p>
      </LegalSection>

      <LegalSection title="10. Contact">
        <p>
          For questions about these terms, please{' '}
          <a href="/contact" className="text-brand-cyan underline">contact us</a>.
        </p>
      </LegalSection>
    </LegalPageLayout>
  )
}
