const { chromium } = require('playwright')
;(async () => {
  const b = await chromium.launch({ headless: true })
  const p = await (await b.newContext({ viewport: { width: 1440, height: 900 } })).newPage()
  await p.goto('http://localhost:3003/login', { waitUntil: 'domcontentloaded' })
  await p.waitForLoadState('networkidle').catch(() => {})
  await p.locator('input[type="email"]').fill('accept.teacher@schemeknit.test')
  await p.locator('input[type="password"]').fill('Accept#2026')
  await p.getByRole('button', { name: 'Sign In' }).click()
  await p.waitForURL(/dashboard/, { timeout: 30000 })
  await p.waitForLoadState('networkidle').catch(() => {})
  await p.waitForTimeout(2500)
  const html = await p.locator('nav[aria-label="Primary"]').innerHTML().catch((e) => 'ERR: ' + e.message)
  console.log('PRIMARY NAV HTML:', html.slice(0, 1600))
  const hrefs = await p.locator('nav a').evaluateAll((as) => as.map((a) => a.getAttribute('href'))).catch((e) => e.message)
  console.log('NAV HREFS:', JSON.stringify(hrefs))
  const weekly = await p.locator('a[href*="weekly"]').count()
  console.log('weekly anchors:', weekly)
  await b.close()
})()
