#!/usr/bin/env python3
"""
Stage the canonical SchemeKnit icon for the desktop build.

The master brand mark is generated by assets/brand/generate_brand_assets.py
(one symbol shared by the web favicon, PWA icons and the Windows EXE). This
script copies the canonical Windows ICO/PNG into desktop/assets so the
Electron/NSIS packaging picks up the master mark. It does NOT rebuild the
installer.
"""
import shutil
from pathlib import Path

BRAND = Path(__file__).resolve().parent.parent / "assets" / "brand"
ASSETS = Path(__file__).resolve().parent / "assets"


def stage_icon():
    ASSETS.mkdir(parents=True, exist_ok=True)
    ico_src = BRAND / "schemeknit-windows.ico"
    png_src = BRAND / "schemeknit-mark-512-square.png"
    if not ico_src.is_file():
        raise SystemExit(f"Canonical icon missing: run {BRAND / 'generate_brand_assets.py'} first")
    shutil.copy2(ico_src, ASSETS / "icon.ico")
    shutil.copy2(png_src, ASSETS / "icon.png")
    print(f"Staged canonical SchemeKnit icon -> {ASSETS / 'icon.ico'}")
    print(f"Staged canonical SchemeKnit mark -> {ASSETS / 'icon.png'}")


if __name__ == "__main__":
    stage_icon()
